remote_theme: pmarsceill/just-the-docs
color_scheme: dark
title: ENG1 - Team 8
logo: "/logo.png"
aux_links:
  "Game repository":
    - "//github.com/ENG1-Team-8/Dragon-Race-2"
footer_content: "Copyright &copy; 2020 The 8-Team, Hard G for GIFs.</a>"
